/**
 * Bug Tracker Template Generator
 * Creates a templated markdown file for documenting bugs found during output review
 */

import fs from 'fs/promises';
import path from 'path';

export interface BugTrackerOptions {
  runTimestamp: string;
  outputFolder: string;
  datasetName?: string;
}

/**
 * Generate the bug tracker template markdown content
 */
export function generateBugTrackerContent(options: BugTrackerOptions): string {
  const { runTimestamp, datasetName } = options;
  const displayName = datasetName || 'Unknown Dataset';

  return `# Bug Tracker - Run ${runTimestamp}

**Dataset**: ${displayName}
**Created**: ${new Date().toISOString()}
**Status**: Pending Review

---

## How to Use This File

1. Review the output files in this folder
2. Document any bugs found using the template below
3. Update the Summary table as you go
4. Mark status as "Reviewed" when complete

---

## Quick Add Template

Copy this template for each bug found:

\`\`\`markdown
### Bug X: [Short description]

**Category**: [Data Map | Banner | Crosstab | R Script | Other]
**Severity**: [Critical | High | Medium | Low]
**Affected**: [File or variable names]

**Current behavior**:
[What happened]

**Expected behavior**:
[What should happen]

**Root cause** (if known):
[Why it happened]

**Status**: [ ] Not Fixed  [ ] Fixed  [ ] Won't Fix
\`\`\`

---

## Data Map Bugs

<!-- Add Data Map related bugs here -->

---

## Banner Plan Bugs

<!-- Add Banner Plan related bugs here -->

---

## Crosstab/Validation Bugs

<!-- Add Crosstab Agent related bugs here -->

---

## R Script Bugs

<!-- Add R script generation related bugs here -->

---

## Other Issues

<!-- Add any other issues here -->

---

## Summary

| Bug | Category | Severity | Status | Description |
|-----|----------|----------|--------|-------------|
| - | - | - | - | No bugs documented yet |

---

## Review Notes

**Reviewer**:
**Review Date**:
**Overall Assessment**:

---

*Generated by TabulateAI - ${runTimestamp}*
`;
}

/**
 * Create the bug tracker template file in the output folder
 */
export async function createBugTrackerTemplate(options: BugTrackerOptions): Promise<string> {
  const { runTimestamp, outputFolder } = options;

  const outputDir = path.join(process.cwd(), 'temp-outputs', outputFolder);
  await fs.mkdir(outputDir, { recursive: true });

  const filename = `bugs-${runTimestamp}.md`;
  const filePath = path.join(outputDir, filename);

  const content = generateBugTrackerContent(options);
  await fs.writeFile(filePath, content, 'utf-8');

  console.log(`[BugTracker] Template created: ${filename}`);

  return filePath;
}

/**
 * Check if bug tracker already exists for this run
 */
export async function bugTrackerExists(outputFolder: string, runTimestamp: string): Promise<boolean> {
  const outputDir = path.join(process.cwd(), 'temp-outputs', outputFolder);
  const filename = `bugs-${runTimestamp}.md`;
  const filePath = path.join(outputDir, filename);

  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
