/**
 * ZeroBaseValidator
 *
 * Evaluates filter expressions against the actual .sav data via a lightweight
 * R subprocess. Detects zero-base filters (expressions that match 0 respondents)
 * before they reach the output.
 *
 * Pattern: follows DistributionCalculator.ts R subprocess spawn pattern.
 * Security: all expressions pass through sanitizeRExpression() before R interpolation.
 */

/**
 * @deprecated Not needed — DeterministicBaseEngine uses real data by construction.
 * No AI-generated filters to validate.
 * This file is retained for reference only. Do not invoke from active pipeline code.
 */

import { spawn } from 'child_process';
import { existsSync, writeFileSync, unlinkSync } from 'fs';
import path from 'path';
import { sanitizeRExpression } from '../r/sanitizeRExpression';
import type { TableFilter } from '../../schemas/skipLogicSchema';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FilterBaseCount {
  /** Composite ID: "ruleId::questionId" */
  filterId: string;
  questionId: string;
  ruleId: string;
  expression: string;
  /** Number of respondents matching the expression; -1 if R evaluation error */
  respondentCount: number;
  totalN: number;
  isZeroBase: boolean;
}

export interface ZeroBaseValidationResult {
  counts: FilterBaseCount[];
  zeroBaseFilters: FilterBaseCount[];
  durationMs: number;
}

// ---------------------------------------------------------------------------
// Internal: collect unique expressions
// ---------------------------------------------------------------------------

interface ExpressionEntry {
  filterId: string;
  questionId: string;
  ruleId: string;
  expression: string;
  /** Whether this is one split among many for the same ruleId+questionId */
  isSplit: boolean;
}

/**
 * Collect all unique non-empty filter expressions from a set of TableFilters.
 * Includes primary filterExpression, split expressions, and column-split expressions.
 */
export function collectFilterExpressions(filters: TableFilter[]): ExpressionEntry[] {
  const entries: ExpressionEntry[] = [];

  for (const f of filters) {
    const filterId = `${f.ruleId}::${f.questionId}`;

    // Primary expression
    if (f.filterExpression && f.filterExpression.trim() !== '') {
      entries.push({
        filterId,
        questionId: f.questionId,
        ruleId: f.ruleId,
        expression: f.filterExpression.trim(),
        isSplit: false,
      });
    }

    // Split expressions
    for (const s of f.splits || []) {
      if (s.filterExpression && s.filterExpression.trim() !== '') {
        entries.push({
          filterId: `${filterId}::split::${s.splitLabel || s.filterExpression.slice(0, 30)}`,
          questionId: f.questionId,
          ruleId: f.ruleId,
          expression: s.filterExpression.trim(),
          isSplit: true,
        });
      }
    }

    // Column-split expressions
    for (const cs of f.columnSplits || []) {
      if (cs.filterExpression && cs.filterExpression.trim() !== '') {
        entries.push({
          filterId: `${filterId}::colsplit::${cs.splitLabel || cs.filterExpression.slice(0, 30)}`,
          questionId: f.questionId,
          ruleId: f.ruleId,
          expression: cs.filterExpression.trim(),
          isSplit: true,
        });
      }
    }
  }

  return entries;
}

// ---------------------------------------------------------------------------
// Internal: R script generation
// ---------------------------------------------------------------------------

function generateValidationScript(spssPath: string, expressions: ExpressionEntry[]): string {
  const escapedPath = spssPath.replace(/\\/g, '/');

  // Build R expression evaluation blocks
  const evalBlocks = expressions.map((entry, i) => {
    // Expression is already sanitized at the call site
    return `
  tryCatch({
    count <- sum(with(data, ${entry.expression}), na.rm = TRUE)
    results[[${i + 1}]] <- list(
      index = ${i},
      filterId = ${JSON.stringify(entry.filterId)},
      respondentCount = as.integer(count),
      totalN = totalN,
      error = ""
    )
  }, error = function(e) {
    results[[${i + 1}]] <- list(
      index = ${i},
      filterId = ${JSON.stringify(entry.filterId)},
      respondentCount = -1L,
      totalN = totalN,
      error = conditionMessage(e)
    )
  })`;
  });

  return `# Zero-base filter validation
# Auto-generated by TabulateAI

suppressPackageStartupMessages({
  library(haven)
  library(jsonlite)
})

# Read SPSS file
data <- tryCatch(
  read_sav("${escapedPath}"),
  error = function(e) {
    cat(toJSON(list(error = paste("Failed to read .sav:", conditionMessage(e))), auto_unbox = TRUE))
    quit(status = 0)
  }
)

totalN <- nrow(data)
results <- vector("list", ${expressions.length})

${evalBlocks.join('\n')}

cat(toJSON(list(totalN = totalN, results = results), auto_unbox = TRUE))
`;
}

// ---------------------------------------------------------------------------
// Internal: find R
// ---------------------------------------------------------------------------

function findRscript(): string {
  const rPaths = [
    '/opt/homebrew/bin/Rscript',
    '/usr/local/bin/Rscript',
    '/usr/bin/Rscript',
    'Rscript',
  ];

  for (const rPath of rPaths) {
    if (rPath === 'Rscript' || existsSync(rPath)) {
      return rPath;
    }
  }
  return 'Rscript';
}

// ---------------------------------------------------------------------------
// Internal: execute R script
// ---------------------------------------------------------------------------

interface RValidationOutput {
  totalN: number;
  results: Array<{
    index: number;
    filterId: string;
    respondentCount: number;
    totalN: number;
    error: string;
  }>;
  error?: string;
}

function executeRScript(scriptPath: string): Promise<RValidationOutput> {
  return new Promise((resolve, reject) => {
    const rCommand = findRscript();
    const proc = spawn(rCommand, [scriptPath]);
    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (d: Buffer) => (stdout += d));
    proc.stderr.on('data', (d: Buffer) => (stderr += d));

    proc.on('close', (code) => {
      // Clean up script file
      try { unlinkSync(scriptPath); } catch { /* ignore */ }

      if (code !== 0) {
        reject(new Error(`R zero-base validation failed (code ${code}): ${stderr.substring(0, 500)}`));
      } else {
        try {
          const parsed = JSON.parse(stdout) as RValidationOutput;
          if (parsed.error) {
            reject(new Error(`R validation error: ${parsed.error}`));
          } else {
            resolve(parsed);
          }
        } catch {
          reject(new Error(`Failed to parse R validation output: ${stdout.substring(0, 200)}`));
        }
      }
    });

    proc.on('error', (err) => {
      try { unlinkSync(scriptPath); } catch { /* ignore */ }
      reject(new Error(`Failed to spawn R process for zero-base validation: ${err.message}`));
    });
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Validate filter expressions against actual .sav data.
 *
 * For split-based filters, only flags as zero-base when ALL splits for a given
 * ruleId+questionId produce zero respondents (a single zero split may be legitimate).
 *
 * If R fails entirely, returns all counts as -1 (does not block the pipeline).
 */
export async function validateFilterBases(
  filters: TableFilter[],
  spssPath: string,
  outputDir: string,
): Promise<ZeroBaseValidationResult> {
  console.warn('[DEPRECATED] validateFilterBases() called — this should not be invoked in the active pipeline. Use DeterministicBaseEngine instead.');
  const startTime = Date.now();

  // Collect all expressions
  const entries = collectFilterExpressions(filters);

  if (entries.length === 0) {
    return { counts: [], zeroBaseFilters: [], durationMs: Date.now() - startTime };
  }

  // Sanitize expressions — skip any that fail
  const safeEntries: ExpressionEntry[] = [];
  const unsafeEntries: FilterBaseCount[] = [];

  for (const entry of entries) {
    const result = sanitizeRExpression(entry.expression);
    if (result.safe) {
      safeEntries.push(entry);
    } else {
      console.warn(
        `[ZeroBaseValidator] Skipping unsafe expression for ${entry.filterId}: ${result.error}`
      );
      unsafeEntries.push({
        filterId: entry.filterId,
        questionId: entry.questionId,
        ruleId: entry.ruleId,
        expression: entry.expression,
        respondentCount: -1,
        totalN: 0,
        isZeroBase: false,
      });
    }
  }

  if (safeEntries.length === 0) {
    return {
      counts: unsafeEntries,
      zeroBaseFilters: [],
      durationMs: Date.now() - startTime,
    };
  }

  // Generate and execute R script
  const rScript = generateValidationScript(spssPath, safeEntries);
  const scriptPath = path.join(outputDir, 'zero_base_validation.R');
  writeFileSync(scriptPath, rScript);

  let rOutput: RValidationOutput;
  try {
    rOutput = await executeRScript(scriptPath);
  } catch (err) {
    // R failed entirely — return all as -1, don't block pipeline
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.warn(`[ZeroBaseValidator] R execution failed: ${errorMsg}. Returning -1 for all filters.`);

    const fallbackCounts: FilterBaseCount[] = safeEntries.map(entry => ({
      filterId: entry.filterId,
      questionId: entry.questionId,
      ruleId: entry.ruleId,
      expression: entry.expression,
      respondentCount: -1,
      totalN: 0,
      isZeroBase: false,
    }));

    return {
      counts: [...fallbackCounts, ...unsafeEntries],
      zeroBaseFilters: [],
      durationMs: Date.now() - startTime,
    };
  }

  // Map R results back to FilterBaseCount
  const counts: FilterBaseCount[] = [];
  for (let i = 0; i < safeEntries.length; i++) {
    const entry = safeEntries[i];
    const rResult = rOutput.results[i];
    const respondentCount = rResult?.respondentCount ?? -1;
    const totalN = rResult?.totalN ?? rOutput.totalN;

    counts.push({
      filterId: entry.filterId,
      questionId: entry.questionId,
      ruleId: entry.ruleId,
      expression: entry.expression,
      respondentCount,
      totalN,
      isZeroBase: respondentCount === 0,
    });
  }

  // Add back unsafe entries
  counts.push(...unsafeEntries);

  // Determine zero-base filters
  // For split-based filters: only flag when ALL splits for a ruleId+questionId are zero
  const zeroBaseFilters: FilterBaseCount[] = [];

  // Group by ruleId+questionId to handle split logic
  const groupedBySplitKey = new Map<string, { splits: FilterBaseCount[]; primary: FilterBaseCount | null }>();

  for (const count of counts) {
    const entry = entries.find(e => e.filterId === count.filterId);
    const groupKey = `${count.ruleId}::${count.questionId}`;

    if (!groupedBySplitKey.has(groupKey)) {
      groupedBySplitKey.set(groupKey, { splits: [], primary: null });
    }

    const group = groupedBySplitKey.get(groupKey)!;
    if (entry?.isSplit) {
      group.splits.push(count);
    } else {
      group.primary = count;
    }
  }

  for (const [, group] of groupedBySplitKey) {
    // Primary (non-split) filters: flag if zero-base
    if (group.primary && group.primary.isZeroBase) {
      zeroBaseFilters.push(group.primary);
    }

    // Split filters: flag only when ALL splits are zero (or errored)
    if (group.splits.length > 0) {
      const allZeroOrError = group.splits.every(s => s.respondentCount === 0 || s.respondentCount === -1);
      const hasAtLeastOneZero = group.splits.some(s => s.respondentCount === 0);
      if (allZeroOrError && hasAtLeastOneZero) {
        // Add all zero-base splits
        for (const split of group.splits) {
          if (split.isZeroBase) {
            zeroBaseFilters.push(split);
          }
        }
      }
    }
  }

  const durationMs = Date.now() - startTime;
  console.log(
    `[ZeroBaseValidator] Validated ${counts.length} expressions in ${durationMs}ms. ` +
    `Zero-base: ${zeroBaseFilters.length}`
  );

  return { counts, zeroBaseFilters, durationMs };
}
