import {
  WinCrossParseDiagnosticsSchema,
  WinCrossPreferenceProfileSchema,
  WinCrossRawJobModelSchema,
  type WinCrossParseDiagnostics,
  type WinCrossPreferenceProfile,
  type WinCrossRawJobModel,
} from '@/lib/exportData/types';

interface ParsedSections {
  order: string[];
  sections: Record<string, string[]>;
}

export interface ParseWinCrossPreferenceResult {
  raw: WinCrossRawJobModel;
  profile: WinCrossPreferenceProfile;
  diagnostics: WinCrossParseDiagnostics;
}

export function parseWinCrossPreferenceJob(input: string | Buffer): ParseWinCrossPreferenceResult {
  const raw = parseRawWinCrossJob(input);
  const diagnostics = buildParseDiagnostics(raw);
  const profile = buildPreferenceProfile(raw);

  return { raw, profile, diagnostics };
}

export function parseRawWinCrossJob(input: string | Buffer): WinCrossRawJobModel {
  const decoded = decodeWinCrossInput(input);
  const parsed = splitSections(decoded.text);

  const versionLines = parsed.sections.VERSION ?? [];
  const preferences = parsed.sections.PREFERENCES ?? [];
  const sigFooter = parsed.sections.SIGFOOTER ?? [];
  const banners = parsed.sections.BANNERS ?? [];
  const tables = parsed.sections.TABLES ?? [];

  const tablePatternHints = {
    tableCount: tables.filter((line) => /^T\d+\^\d+/i.test(line)).length,
    useCount: tables.filter((line) => /^USE\s*=\s*/i.test(line)).length,
    afCount: tables.filter((line) => /^AF\s*=\s*/i.test(line)).length,
    sbaseCount: tables.filter((line) => /^SBase\s*:/i.test(line)).length,
  };

  return WinCrossRawJobModelSchema.parse({
    encoding: decoded.encoding,
    sectionOrder: parsed.order,
    rawSections: parsed.sections,
    versionLines,
    preferenceSection: classifyPreferenceSection(preferences),
    sigFooterLines: sigFooter,
    bannerSection: classifyBannerSection(banners),
    tableSection: classifyTableSection(tables),
    titleLines: parsed.sections.TITLE ?? [],
    tablePatternHints,
  });
}

export function buildDefaultWinCrossPreferenceProfile(): WinCrossPreferenceProfile {
  return WinCrossPreferenceProfileSchema.parse({
    version: '25.0',
    numericPreferenceVector: '0,0,0,0,0',
    tableOptionSignature: 'OS,OR,OV,OI2,O%',
    defaultTotalLine: 'Total^TN^1',
    preferenceLines: [
      '0,0,0,0,0',
      'SM=Mean,SD=Median,SV=StdDev,SR=StdErr,TN=Total,SB=SBase',
      'OS,OR,OV,OI2,O%',
      'Total^TN^1',
    ],
    tokenDictionary: {
      TN: 'Total',
      SB: 'SBase',
      SM: 'Mean',
      SD: 'Median',
      SV: 'StdDev',
      SR: 'StdErr',
    },
    statsDictionary: {
      SM: 'Mean',
      SD: 'Median',
      SV: 'StdDev',
      SR: 'StdErr',
    },
    sigFooterLines: [
      'Significance tested at 95% confidence level.',
      'Letters indicate statistically significant differences.',
    ],
    bannerLines: [],
    bannerMemberLines: [],
    bannerDisplayLines: [],
    bannerLayoutLines: [],
    titleLines: ['Generated by TabulateAI WinCross exporter'],
    passthroughSections: {
      GLOSSARY: [],
      SIDEBYSIDE: [],
    },
    tableStyleHints: {
      sourceTableCount: 0,
      valueReferenceColumn: null,
      statLabelCaretColumn: null,
      netRowSuffixToken: null,
      headerLeadingSpaces: null,
      headerRowPattern: 'none',
      notes: [],
    },
    tablePatternHints: {
      tableCount: 0,
      useCount: 0,
      afCount: 0,
      sbaseCount: 0,
    },
  });
}

function decodeWinCrossInput(input: string | Buffer): { text: string; encoding: 'utf16le' | 'utf8' | 'unknown' } {
  if (typeof input === 'string') {
    return { text: input, encoding: 'utf8' };
  }

  if (input.length >= 2 && input[0] === 0xff && input[1] === 0xfe) {
    return { text: input.subarray(2).toString('utf16le'), encoding: 'utf16le' };
  }
  if (input.length >= 2 && input[0] === 0xfe && input[1] === 0xff) {
    // UTF-16 BE BOM
    const swapped = Buffer.from(input.subarray(2));
    for (let i = 0; i + 1 < swapped.length; i += 2) {
      const a = swapped[i];
      swapped[i] = swapped[i + 1];
      swapped[i + 1] = a;
    }
    return { text: swapped.toString('utf16le'), encoding: 'utf16le' };
  }

  // Heuristic: UTF-16LE text usually contains many null bytes in odd positions.
  let oddNullCount = 0;
  for (let i = 1; i < Math.min(input.length, 2000); i += 2) {
    if (input[i] === 0x00) oddNullCount += 1;
  }
  const looksUtf16 = oddNullCount > 20;

  if (looksUtf16) {
    return { text: input.toString('utf16le'), encoding: 'utf16le' };
  }
  return { text: input.toString('utf8'), encoding: 'utf8' };
}

function buildParseDiagnostics(raw: WinCrossRawJobModel): WinCrossParseDiagnostics {
  const warnings: string[] = [];
  const errors: string[] = [];

  if (raw.sectionOrder.length === 0) {
    warnings.push('No [SECTION] headers were detected in the WinCross preference input.');
  }
  if (raw.preferenceSection.rawLines.length > 0 && !raw.preferenceSection.vectorLine) {
    warnings.push('Could not confidently identify the primary [PREFERENCES] vector line.');
  }
  if (
    raw.preferenceSection.vectorLine
    && /[A-Za-z]/.test(raw.preferenceSection.vectorLine)
    && !/^\d+(\s*,\s*\d+)+$/.test(raw.preferenceSection.vectorLine)
  ) {
    warnings.push('Detected a mixed-type [PREFERENCES] vector line; preserving raw text for downstream normalization.');
  }
  if (raw.bannerSection.layoutDirectiveLines.length > 0 && raw.bannerSection.memberLines.length > 0) {
    warnings.push('Banner section contains both layout directives and member lines; application must separate layout from run-specific membership.');
  }

  return WinCrossParseDiagnosticsSchema.parse({
    warnings,
    errors,
    sectionNames: raw.sectionOrder,
    encoding: raw.encoding,
  });
}

function buildPreferenceProfile(
  raw: WinCrossRawJobModel,
): WinCrossPreferenceProfile {
  const tokenDictionary: Record<string, string> = {};
  const statsDictionary: Record<string, string> = {};

  for (const assignmentLine of raw.preferenceSection.tokenAssignmentLines) {
    extractTokenAssignments(assignmentLine, tokenDictionary, statsDictionary);
  }

  applyStatLabelLines(raw.preferenceSection.statLabelLines, statsDictionary);

  const passthroughSections: Record<string, string[]> = {};
  for (const sectionName of raw.sectionOrder) {
    if (['VERSION', 'PREFERENCES', 'SIGFOOTER', 'BANNERS', 'TITLE'].includes(sectionName)) continue;
    passthroughSections[sectionName] = raw.rawSections[sectionName] ?? [];
  }

  return WinCrossPreferenceProfileSchema.parse({
    version: raw.versionLines[0]?.trim() || null,
    numericPreferenceVector: raw.preferenceSection.vectorLine,
    tableOptionSignature: raw.preferenceSection.tableOptionSignatureLine,
    defaultTotalLine: raw.preferenceSection.defaultTotalLine,
    preferenceLines: raw.preferenceSection.rawLines,
    tokenDictionary,
    statsDictionary,
    sigFooterLines: raw.sigFooterLines,
    bannerLines: raw.bannerSection.rawLines,
    bannerMemberLines: raw.bannerSection.memberLogicLines,
    bannerDisplayLines: raw.bannerSection.displayRowLines,
    bannerLayoutLines: raw.bannerSection.layoutDirectiveLines,
    titleLines: raw.titleLines,
    passthroughSections,
    tableStyleHints: raw.tableSection.styleHints,
    tablePatternHints: raw.tablePatternHints,
  });
}

function splitSections(text: string): ParsedSections {
  const lines = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  const sections: Record<string, string[]> = {};
  const order: string[] = [];
  let current = 'ROOT';

  for (const raw of lines) {
    const line = raw.replace(/\u0000/g, '');
    const sectionMatch = line.trim().match(/^\[([^\]]+)\]$/);
    if (sectionMatch) {
      current = sectionMatch[1].trim().toUpperCase();
      if (!sections[current]) {
        sections[current] = [];
        order.push(current);
      }
      continue;
    }

    if (!sections[current]) {
      sections[current] = [];
      order.push(current);
    }
    sections[current].push(line);
  }

  return { sections, order };
}

function classifyPreferenceSection(lines: string[]) {
  const tokenAssignmentLines: string[] = [];
  const statLabelLines: string[] = [];
  const otherLines: string[] = [];
  let vectorLine: string | null = null;
  let tableOptionSignatureLine: string | null = null;
  let defaultTotalLine: string | null = null;

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;

    if (!tableOptionSignatureLine && looksLikeOptionSignature(line)) {
      tableOptionSignatureLine = line;
      continue;
    }

    if (!defaultTotalLine && /\^\s*TN\s*\^/i.test(line)) {
      defaultTotalLine = line;
      continue;
    }

    if (!vectorLine && looksLikePreferenceVector(line)) {
      vectorLine = line;
      continue;
    }

    if (line.includes('=')) {
      tokenAssignmentLines.push(line);
      continue;
    }

    if (line.includes(',')) {
      statLabelLines.push(line);
      continue;
    }

    otherLines.push(line);
  }

  return {
    rawLines: lines,
    vectorLine,
    tableOptionSignatureLine,
    defaultTotalLine,
    tokenAssignmentLines,
    statLabelLines,
    otherLines,
  };
}

function classifyBannerSection(lines: string[]) {
  const layoutDirectiveLines: string[] = [];
  const memberLines: string[] = [];
  const memberLogicLines: string[] = [];
  const displayRowLines: string[] = [];
  const otherLines: string[] = [];
  let inDisplayRows = false;

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith('*') || line.startsWith(';') || /^[A-Z]{1,4}\s*:/.test(line)) {
      layoutDirectiveLines.push(rawLine);
      continue;
    }

    if (!inDisplayRows && looksLikeBannerDisplayBoundary(rawLine)) {
      inDisplayRows = true;
    }

    if (inDisplayRows) {
      displayRowLines.push(rawLine);
      continue;
    }

    if (line.includes('^') || line.includes('(') || /[A-Za-z]/.test(line)) {
      memberLines.push(rawLine);
      memberLogicLines.push(rawLine);
      continue;
    }

    otherLines.push(rawLine);
  }

  return {
    rawLines: lines,
    layoutDirectiveLines,
    memberLines,
    memberLogicLines,
    displayRowLines,
    otherLines,
  };
}

function classifyTableSection(lines: string[]) {
  const tableBlocks = splitTableBlocks(lines);
  const valueReferenceColumns: number[] = [];
  const statLabelCaretColumns: number[] = [];
  const netRowSuffixTokens: string[] = [];
  const headerLeadingSpaces: number[] = [];
  const headerPatterns: Array<'none' | 'leading_label_only' | 'sectioned_label_only' | 'trailing_label_only' | 'mixed_or_unsafe'> = [];
  const notes: string[] = [];

  for (const block of tableBlocks) {
    const blockAnalysis = analyzeTableBlock(block);
    valueReferenceColumns.push(...blockAnalysis.valueReferenceColumns);
    statLabelCaretColumns.push(...blockAnalysis.statLabelCaretColumns);
    netRowSuffixTokens.push(...blockAnalysis.netRowSuffixTokens);
    headerLeadingSpaces.push(...blockAnalysis.headerLeadingSpaces);
    headerPatterns.push(blockAnalysis.headerPattern);
  }

  const headerPattern = summarizeHeaderPattern(headerPatterns);
  if (headerPattern === 'mixed_or_unsafe') {
    notes.push('Source table header-row placement varied across uploaded tables and was not promoted to a portable remapping rule.');
  }
  if (valueReferenceColumns.length === 0) {
    notes.push('No stable source value-row reference alignment hint was detected.');
  }
  if (statLabelCaretColumns.length === 0) {
    notes.push('No stable source single-variable stat label alignment hint was detected.');
  }

  return {
    rawLines: lines,
    styleHints: {
      sourceTableCount: tableBlocks.length,
      valueReferenceColumn: findModalNumber(valueReferenceColumns),
      statLabelCaretColumn: findModalNumber(statLabelCaretColumns),
      netRowSuffixToken: findModalToken(netRowSuffixTokens),
      headerLeadingSpaces: findModalNumber(headerLeadingSpaces),
      headerRowPattern: headerPattern,
      notes,
    },
  };
}

function looksLikeBannerDisplayBoundary(rawLine: string): boolean {
  const line = rawLine.replace(/\t/g, '    ').trim();
  if (!line) return false;
  if (/^[.\-_= ]+$/.test(line)) return true;
  if (line.includes('^')) return false;

  const spacedSegments = rawLine.trim().split(/\s{2,}/).filter((segment) => segment.trim().length > 0);
  if (spacedSegments.length >= 2) {
    return true;
  }

  return false;
}

function splitTableBlocks(lines: string[]): string[][] {
  const blocks: string[][] = [];
  let current: string[] = [];

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();
    if (/^T\d+\^\d+/i.test(trimmed)) {
      if (current.length > 0) {
        blocks.push(current);
      }
      current = [rawLine];
      continue;
    }
    if (current.length > 0) {
      current.push(rawLine);
    }
  }

  if (current.length > 0) {
    blocks.push(current);
  }

  return blocks;
}

function analyzeTableBlock(block: string[]): {
  valueReferenceColumns: number[];
  statLabelCaretColumns: number[];
  netRowSuffixTokens: string[];
  headerLeadingSpaces: number[];
  headerPattern: 'none' | 'leading_label_only' | 'sectioned_label_only' | 'trailing_label_only' | 'mixed_or_unsafe';
} {
  const valueReferenceColumns: number[] = [];
  const statLabelCaretColumns: number[] = [];
  const netRowSuffixTokens: string[] = [];
  const headerLeadingSpaces: number[] = [];
  let bodyRowCount = 0;
  let sawLeadingHeader = false;
  let sawSectionedHeader = false;

  for (let index = 1; index < block.length; index += 1) {
    const rawLine = block[index] ?? '';
    const line = rawLine.trim();
    if (!line) continue;
    if (looksLikeOptionSignature(line)) continue;
    if (/^SBase\s*:/i.test(line)) continue;
    if (/^USE\s*=/i.test(line)) continue;
    if (/^AF\s*=/i.test(line)) continue;
    if (/^DATA\s*=/i.test(line)) continue;
    if (isWinCrossTitleOrSubtitleLine(line)) continue;
    if (/\^\s*TN\s*\^/i.test(line)) continue;
    if (!line.includes('^')) continue;

    if (isLabelOnlyTableHeaderRow(line)) {
      headerLeadingSpaces.push(rawLine.length - rawLine.trimStart().length);
      if (bodyRowCount === 0) {
        sawLeadingHeader = true;
      } else {
        sawSectionedHeader = true;
      }
      continue;
    }

    const firstCaretIndex = rawLine.indexOf('^');
    if (firstCaretIndex < 0) continue;
    const secondFieldStart = findSecondFieldStart(rawLine);
    const isStatRow = isStatTableRow(line);
    const netSuffixToken = extractTrailingToken(line);
    if (/NET\s*\(/i.test(line) && netSuffixToken) {
      netRowSuffixTokens.push(netSuffixToken);
    }
    const isSingleVariableStatLabelRow = (
      isStatRow
      && secondFieldStart === firstCaretIndex + 1
      && firstCaretIndex > rawLine.slice(0, firstCaretIndex).trimEnd().length
    );

    if (isSingleVariableStatLabelRow) {
      statLabelCaretColumns.push(firstCaretIndex);
      bodyRowCount += 1;
      continue;
    }

    if (secondFieldStart !== null) {
      valueReferenceColumns.push(secondFieldStart);
    }
    bodyRowCount += 1;
  }

  if (bodyRowCount > 0 && sawSectionedHeader) {
    return {
      valueReferenceColumns,
      statLabelCaretColumns,
      netRowSuffixTokens,
      headerLeadingSpaces,
      headerPattern: 'sectioned_label_only',
    };
  }
  if (bodyRowCount > 0 && sawLeadingHeader) {
    return {
      valueReferenceColumns,
      statLabelCaretColumns,
      netRowSuffixTokens,
      headerLeadingSpaces,
      headerPattern: 'leading_label_only',
    };
  }
  if (bodyRowCount === 0 && (sawLeadingHeader || sawSectionedHeader)) {
    return {
      valueReferenceColumns,
      statLabelCaretColumns,
      netRowSuffixTokens,
      headerLeadingSpaces,
      headerPattern: 'trailing_label_only',
    };
  }

  return {
    valueReferenceColumns,
    statLabelCaretColumns,
    netRowSuffixTokens,
    headerLeadingSpaces,
    headerPattern: 'none',
  };
}

function summarizeHeaderPattern(
  patterns: Array<'none' | 'leading_label_only' | 'sectioned_label_only' | 'trailing_label_only' | 'mixed_or_unsafe'>,
): 'none' | 'leading_label_only' | 'sectioned_label_only' | 'trailing_label_only' | 'mixed_or_unsafe' {
  const nonNone = patterns.filter((pattern) => pattern !== 'none');
  if (nonNone.length === 0) return 'none';
  const unique = new Set(nonNone);
  if (unique.size === 1) {
    return nonNone[0] ?? 'none';
  }
  return 'mixed_or_unsafe';
}

function findSecondFieldStart(rawLine: string): number | null {
  const firstCaretIndex = rawLine.indexOf('^');
  if (firstCaretIndex < 0) return null;
  const afterCaret = rawLine.slice(firstCaretIndex + 1);
  const offset = afterCaret.search(/\S/);
  if (offset < 0) return null;
  const start = firstCaretIndex + 1 + offset;
  return rawLine[start] === '^' ? null : start;
}

function isLabelOnlyTableHeaderRow(line: string): boolean {
  return /^[^^]+\^\s*$/.test(line);
}

function isStatTableRow(line: string): boolean {
  return /\^(SM|SD|SV|SR|MN|MD|SE|STD|N|GM)\s*$/i.test(line);
}

function isWinCrossTitleOrSubtitleLine(line: string): boolean {
  return !line.includes('^') && !line.includes(',') && !line.includes('=');
}

function findModalNumber(values: number[]): number | null {
  if (values.length === 0) return null;

  const counts = new Map<number, number>();
  for (const value of values) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  let bestValue: number | null = null;
  let bestCount = 0;
  for (const [value, count] of counts.entries()) {
    if (count > bestCount) {
      bestValue = value;
      bestCount = count;
    }
  }

  return bestValue;
}

function findModalToken(values: string[]): string | null {
  if (values.length === 0) return null;

  const counts = new Map<string, number>();
  for (const value of values) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  let bestValue: string | null = null;
  let bestCount = 0;
  for (const [value, count] of counts.entries()) {
    if (count > bestCount) {
      bestValue = value;
      bestCount = count;
    }
  }

  return bestValue;
}

function extractTrailingToken(line: string): string | null {
  const parts = line.split('^').map((part) => part.trim()).filter((part) => part.length > 0);
  if (parts.length < 2) return null;
  const candidate = parts[parts.length - 1] ?? '';
  return /^[A-Z][A-Z0-9]*$/i.test(candidate) ? candidate.toUpperCase() : null;
}

function looksLikeOptionSignature(line: string): boolean {
  return /(\bOS\b|\bOR\b|\bOV\b|\bO%\b)/.test(line) && line.includes(',');
}

function looksLikePreferenceVector(line: string): boolean {
  if (!line.includes(',')) return false;
  if (line.includes('=')) return false;
  if (looksLikeOptionSignature(line)) return false;
  if (/\^\s*TN\s*\^/i.test(line)) return false;
  return true;
}

function extractTokenAssignments(
  line: string,
  tokenDictionary: Record<string, string>,
  statsDictionary: Record<string, string>,
): void {
  for (const part of line.split(',')) {
    const token = part.trim();
    if (!token || !token.includes('=')) continue;

    const [rawKey, ...rest] = token.split('=');
    const key = (rawKey ?? '').trim();
    const value = rest.join('=').trim();
    if (!key || !value) continue;

    tokenDictionary[key] = value;
    if (/^(SM|SD|SV|SR|MN|MD|SE|STD|N|GM)$/i.test(key)) {
      statsDictionary[key.toUpperCase()] = value;
    }
  }
}

function applyStatLabelLines(lines: string[], statsDictionary: Record<string, string>): void {
  if (lines.length === 0) return;

  const firstLabels = lines[0]
    .split(',')
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
  const tokenOrder = ['SM', 'SD', 'SV', 'SR', 'N', 'GM'];

  for (let index = 0; index < Math.min(firstLabels.length, tokenOrder.length); index += 1) {
    const token = tokenOrder[index];
    if (!statsDictionary[token]) {
      statsDictionary[token] = firstLabels[index];
    }
  }
}
